---
- name: Install aws-iam-authenticator
  become: false
  command: go get -u -v github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator
  environment:
    GOPATH: "{{ go_path }}"
    PATH: "{{ go_sys_path }}"
  changed_when: false  #Never really know when it updated

